export const APPLICATION_BASE_ROUTE = "/application";

export const pageName = {
  LOGIN: "login",
  MAGIC_LOGIN: "login/magic",
  REGISTRATION: "registration",
  FORGOT_PASSWORD: "forgotPassword",
  RESET_PASSWORD: "resetpassword",
  BORROWER_PORTAL: "borrower",
  START: "start",
  TERMS_OF_USE: "terms-of-use",
  PRIVACY_NOTICE: "privacy-notice",
  ONLINE_PRIVACY_NOTICE: "online-privacy-notice",
  THANKYOU: "thankyou",
};

const {
  LOGIN,
  MAGIC_LOGIN,
  FORGOT_PASSWORD,
  RESET_PASSWORD,
  BORROWER_PORTAL,
  START,
  REGISTRATION,
  TERMS_OF_USE,
  PRIVACY_NOTICE,
  ONLINE_PRIVACY_NOTICE,
  THANKYOU,
} = pageName;

export const routes = {
  HOME: `${APPLICATION_BASE_ROUTE}/`,
  LOGIN: `${APPLICATION_BASE_ROUTE}/${LOGIN}`,
  MAGIC_LOGIN: `${APPLICATION_BASE_ROUTE}/${MAGIC_LOGIN}`,
  REGISTRATION: `${APPLICATION_BASE_ROUTE}/${REGISTRATION}`,
  FORGOT_PASSWORD: `${APPLICATION_BASE_ROUTE}/${LOGIN}/${FORGOT_PASSWORD}`,
  RESET_PASSWORD: `${APPLICATION_BASE_ROUTE}/${RESET_PASSWORD}`,
  BORROWER_PORTAL: `/${BORROWER_PORTAL}/`,
  START: `${APPLICATION_BASE_ROUTE}/${START}/`,
  TERMS_OF_USE: `/${TERMS_OF_USE}`,
  PRIVACY_NOTICE: `/${PRIVACY_NOTICE}`,
  ONLINE_PRIVACY_NOTICE: `/${ONLINE_PRIVACY_NOTICE}`,
  THANKYOU: `${APPLICATION_BASE_ROUTE}/${THANKYOU}`,
};
