export const BASE_ROUTE = "/admin";

export const routes = {
  DASHBOARD: `${BASE_ROUTE}/`,
  APPLICATIONS_DENIED: `${BASE_ROUTE}/applications-denied`,
  APPLICATIONS_ARCHIVED: `${BASE_ROUTE}/applications-archived`,
  APPLICATIONS_CHARGEDOFF: `${BASE_ROUTE}/applications-chargedoff`,
  APPLICATIONS_SETTLED: `${BASE_ROUTE}/applications-settled`,
  CONTRACTS_ACTIVE: `${BASE_ROUTE}/contracts-active`,
  CONTRACTS_COMPLETED: `${BASE_ROUTE}/contracts-completed`,
  CONTRACTS_BANKRUPTSY: `${BASE_ROUTE}/applications-bankruptsy`,
  COLLECTIONS: `${BASE_ROUTE}/collections`,
  FORGOT_PASSWORD: `${BASE_ROUTE}/forgot-password`,
  LEADS_FRESH: `${BASE_ROUTE}/leads-fresh`,
  LEADS_REJECTED: `${BASE_ROUTE}/leads-rejected`,
  LOAN_DETAILS: `${BASE_ROUTE}/loan-details`,
  MANAGE_ADMINS: `${BASE_ROUTE}/manage-admins`,
  MANAGE_LEADS: `${BASE_ROUTE}/manage-leads`,
  NOTIFICATIONS: `${BASE_ROUTE}/notifications`,
  LOGIN: `${BASE_ROUTE}/login`,
  REPORTS: `${BASE_ROUTE}/reports`,
  RESET_PASSWORD: `${BASE_ROUTE}/resetpassword`,
  START_APPLICATION: `${BASE_ROUTE}/new-application`,
  SETTINGS_CREDENTIALS: `${BASE_ROUTE}/settings-credentials`,
  USER_DETAILS: `${BASE_ROUTE}/user-details`,
};
