"use strict";
const rejectReasonText = {
	R01: "Insufficient Funds",
	R02: "Account Closed",
	R03: "No Account/Unable to Locate Account",
	R04: "Invalid Account Number",
	R05: "Improper Debit to Consumer Account",
	R06: "Returned per ODFI's Request",
	R07: "Authorization Revoked by Customer",
	R08: "Payment Stopped",
	R09: "Uncollected Funds",
	R10: "Customer Advises Not Authorized",
	R11: "Check Truncation Entry Returned",
	R12: "Branch Sold to Another DFI",
	R13: "RDFI Not Qualifed to Participate",
	R14: "Account-holder Deceased [Representative Payee Deceased or Unable to Continue in that Capacity]",
	R15: "Beneficiary Deceased [Beneficiary or Account Holder (Other Than a Representative Payee) Deceased]",
	R16: "Account Frozen",
	R17: "File Record Edit Criteria",
	R18: "Improper Effective Entry Date",
	R19: "Amount Field Error",
	R20: "Non Transaction Account",
	R21: "Invalid Company Identification",
	R22: "Invalid Individual ID Number",
	R23: "Credit Entry Refused by Receiver",
	R24: "Duplicate Entry",
	R25: "Addenda Error",
	R26: "Mandatory Field Error",
	R27: "Trace Number Error",
	R28: "Routing Number Check Digit Error",
	R29: "Corporate Customer Advises Not Authorized",
	R230: "RDFI Not Participant in Check Truncation Program",
	R31: "Permissible Return Entry (CCD and CTX only)",
	R32: "RDFI Non-Settlement",
	R33: "Return of XCK Entry",
	R34: "Limited Participation DFI",
	R35: "Return of Improper Debit Entry",
	R36: "Reserved",
	R37: "Reserved",
	R38: "STOP PAY (ARC)",
	R39: "Reserved",
	R40: "Non-Participant in ENR Program (ENR only)",
	R41: "Invalid Transaction Code (ENR only)",
	R42: "Routing Number/Check Digit Error (ENR only)",
	R43: "Invalid DFI Account Number (ENR only)",
	R44: "Invalid Individual ID Number (ENR only)",
	R45: "Invalid Individual Name (ENR only)",
	R46: "Invalid Representative Payee Indicator (ENR only)",
	R47: "Duplicate Enrollment (ENR only)",
	R48: "Reserved",
	R49: "Reserved",
	R50: "State Law Affecting RCK Acceptance",
	R51: "Item is Ineligible, Notice Not Provided, Signatures Not Genuine, Item Altered or Amount of RCK Entry not Accurately Obtained From the Item",
	R52: "Stop Payment",
	R53: "Paper backup missing or not in agreement",
	R54: "Reserved",
	R55: "Reserved",
	R56: "Reserved",
	R57: "Reserved",
	R58: "Reserved",
	R59: "Reserved",
	R90: "State not on Vikings Allowed list",
	R91: "Positive due to Military Scurb",
	R92: "Positive Due to OFAC Scrub",
	R93: "Reject due to Bank Account Scrub",
	R94: "Previous Return history disallows this Transaction (Future Use)",
	R95: "Correction sent previously not yet made",
	R96: "Viking Standard (Check Digit error Non-Conforming Routing Number)",
	C01: "Corrected Account",
	C02: "Corrected Routing",
	C03: "Corrected Routing and Account",
	C04: "Corrected Name",
	C05: "Corrected Tran Code",
	C06: "Corrected Account and Tran Code",
	C07: "Corrected Routing, Account, and Tran Code",
	C08: "Corrected Foreign Routing",
	C09: "Corrected Individual ID Number",
	C10: "Corrected Company Name",
	C11: "Corrected Company ID",
	C12: "Corrected Company Name and Company ID",
	C13: "Addenda Format Error",
	C61: "Misrouted Notification Of Change",
	C62: "Incorrect Trace Number",
	C63: "Incorrect Company Identification Number",
	C64: "Incorrect Individual Identification Number",
	C65: "Incorrectly formatted Corrected Data",
	C66: "Incorrect Discretionary Data",
	C67: "Routing Number not from Original Entry Detail Record",
	C68: "DFI Account Number not from Original Entry Detail Record",
	C69: "Incorrect Transaction Code"
};
const holidays = {
	2018: [ "2018-08-15", "2018-10-02" ],
	2019: [ "2018-08-15", "2018-10-02" ]
};
// ============================Sandbox=====================================
module.exports.actumConfig = {
	csvFilePath: "/assets/ActumCredit/",
	rejectReason: rejectReasonText,
	makepaymentdate: "7",
	holidays: holidays,
	parentId: "ACTUM",
	subId: "MHFTEST",
	creditsubId: "MHFTEST",
	syspass: "bhewjql4320",
	actumUsername: "MHFTEST",
	actumPasswrod: "changeme",
	actumApiUrl: "https://join.actumprocessing.com/cgi-bin/dbs/man_trans.cgi",
	pfiFixedFee: 4,
	pfiPercentFee: 0.5,
	pfiOriginationFee: 25,
	actumMode: "sandbox"
};

// ============================Live=====================================
/* module.exports.actumConfig = {
	csvFilePath:'/assets/ActumCredit/',
	rejectReason : rejectReasonText,
	makepaymentdate:'7',
	holidays:holidays,
	parentId:'ACTUM',
	subId:'PFP002',
	syspass:'fgjkrty563',
	actumUsername:'A20180044_Dev',
	actumPasswrod:'!Patient2018Fi',
	actumApiUrl:'https://join.actumprocessing.com/cgi-bin/dbs/man_trans.cgi',
	pfiFixedFee:4,
	pfiPercentFee:5,
	pfiOriginationFee:25,
	actumMode:'live'
};*/
