module.exports.policies = {
  UserController: {
    clarityInquiry: [],
    stepsTesting: [],
    initiateflinksService: [],
    getFlinkDeliveredData: [],
    registeruser: ["Maintenance", "isAuthenticated"],
    manageproducts: ["Maintenance", "isAuthenticated"],
    registerDevice: ["Maintenance", "validation/User/RegisterDeviceValidation"],
    finalizeUser: [
      "Maintenance",
      "isUserAuthenticated",
      "validation/User/FinalizeValidation",
    ],
    addFundingMethod: ["Maintenance"],
    smsCodeNotification: [
      "Maintenance",
      "isUserAuthenticated",
      "validation/User/SmsCodeNotificationValidation",
    ],
    smsCodeVerification: [
      "Maintenance",
      "isUserAuthenticated",
      "validation/User/SmsCodeVerificationValidation",
    ],
    uploadProfilePicture: ["Maintenance", "isUserAuthenticated", "UploadImage"],
    addScreenName: [
      "Maintenance",
      "isUserAuthenticated",
      "validation/User/AddScreenNameValidation",
    ],
    getUserProfile: ["Maintenance", "isUserAuthenticated"],
    getAllUserAgreements: ["Maintenance", "isUserAuthenticated"],
    changeNotificationStatus: [
      "Maintenance",
      "isUserAuthenticated",
      "validation/User/SmsNotificationStatusValidation",
    ],
    creditLimitRequest: [
      "Maintenance",
      "isUserAuthenticated",
      "validation/User/CreditLimitValidation",
    ],
    updateProfile: [
      "Maintenance",
      "isUserAuthenticated",
      "validation/User/UpdatedInformation",
    ],
    registerNewAdmin: [],
    apiLogin: ["Maintenance", "validation/User/ApiLoginValidation"],
    login: ["Maintenance", "validation/User/LoginValidation"],
    preLogin: ["Maintenance", "isUserAuthenticated"],
    logout: ["Maintenance", "isAuthenticated"],
    getSettingDetail: ["Maintenance", "isUserAuthenticated"],
    updateSettingOfUser: ["Maintenance", "isUserAuthenticated"],
    getUserLoanStatus: ["Maintenance", "isUserAuthenticated"],
    forgetApiPassword: [
      "Maintenance",
      "validation/User/ForgetApiPasswordValidation",
    ],
    changeApiPassword: [
      "Maintenance",
      "validation/User/changeApiPasswordValidation",
    ],
    forgetPasscode: ["Maintenance", "validation/User/ForgetPasscodeValidation"],
    getallUserDetails: ["Maintenance", "isAuthenticated"],
    ajaxManageUserlist: ["Maintenance", "isAuthenticated"],
    resendVerficationlink: ["Maintenance", "isUserAuthenticated"],
    viewUserDetails: ["Maintenance", "isAuthenticated"],
    updateUserStatus: ["Maintenance", "isAuthenticated"],
    deleteUserDetails: ["Maintenance", "isAuthenticated"],
    getAllPaymentManagement: ["Maintenance", "isAuthenticated"],
    getAllLatePaymentManagement: ["Maintenance", "isAuthenticated"],
    changeverifystatus: ["Maintenance", "isAuthenticated"],
    changephoneverifystatus: ["Maintenance", "isAuthenticated"],
    sendverficationlink: ["Maintenance", "isAuthenticated"],
    sendverficationcode: ["Maintenance", "isAuthenticated"],
    updatepushnotification: ["Maintenance", "isUserAuthenticated"],
    removephone: ["Maintenance", "isAuthenticated"],
    changeemail: ["Maintenance", "isAuthenticated"],
    changeAPIEmailaddress: ["Maintenance", "isUserAuthenticated"],
    changephone: ["Maintenance", "isAuthenticated"],
    socialRegisterDevice: [
      "Maintenance",
      "validation/User/SocialRegisterDeviceValidation",
    ],
    finalizeSocialUser: [
      "Maintenance",
      "validation/User/FinalizeSocialUserValidation",
    ],
    userTrackingData: ["Maintenance", "isUserAuthenticated"],
    ajaxUserTrackingList: ["Maintenance", "isAuthenticated"],
    showUserTrackingMap: ["Maintenance", "isAuthenticated"],
    userContactsData: ["Maintenance", "isUserAuthenticated"],
    ajaxUserContactsList: ["Maintenance", "isAuthenticated"],
    userInvitesData: ["Maintenance", "isUserAuthenticated"],
    createstateregulation: [
      "Maintenance",
      "validation/State/CreateLoanStateValidation",
    ],
    createupdateamountcap: [
      "Maintenance",
      "validation/manageproducts/Addamountcapvalidation",
    ],
    updateUserNameDetails: ["Maintenance", "isAuthenticated"],
    updateAddressDetails: ["Maintenance", "isAuthenticated"],
    adminLoginView: ["Maintenance"],
    thankyouView: ["Maintenance"],
    forgetPassword: ["Maintenance"],
    ajaxregisteruserlist: ["Maintenance", "isAuthenticated"],
    maintenanceView: ["CheckMaintenance"],
    newresentinviteemail: ["Maintenance", "isAuthenticated"],
    resetUserDetails: ["Maintenance", "isAuthenticated"],
    getallResetUsers: ["Maintenance", "isAuthenticated"],
    ajaxManageResetUserlist: ["Maintenance", "isAuthenticated"],
    viewResetUserDetails: ["Maintenance", "isAuthenticated"],
    changemobile: ["Maintenance", "isLoginAuthenticated"],
    joinRoom: ["Maintenance"],
    getStates: ["Maintenance"],
    loanDeniedView: ["Maintenance"],
    newHomeView: ["Maintenance"],
    aboutView: ["Maintenance"],
    howItWorksView: ["Maintenance"],
    faqView: ["Maintenance"],
    ratesAndFeesView: ["Maintenance"],
    termsOfUseView: ["Maintenance"],
    optoutView: ["Maintenance"],
    contactView: ["Maintenance"],
    ajaxGetUserList: ["Maintenance", "isAuthenticated"],
  },
  TwilioController: {
    startverification: ["Maintenance"],
    validate: ["Maintenance"],
  },
  AgreementController: {
    createAgreement: [
      "Maintenance",
      "isUserAuthenticated",
      "validation/Agreement/AgreementValidation",
    ],
    getAgreementList: ["Maintenance", "isUserAuthenticated"],
    getAgreement: ["Maintenance", "isUserAuthenticated"],
    agreement: [
      "Maintenance",
      "isAuthenticated",
      "validation/Agreement/AgreementValidation",
    ],
    updateAgreement: [
      "Maintenance",
      "validation/Agreement/UpdateAgreementValidation",
    ],
    agreementList: ["Maintenance", "isAuthenticated", "isUserAuthenticated"],
    createAgreementView: ["Maintenance", "isAuthenticated"],
    getAllAgreement: ["Maintenance", "isAuthenticated"],
    getAgreementDetail: ["Maintenance", "isAuthenticated"],
    UpdateAgreementView: ["Maintenance", "isAuthenticated"],
    deleteAgreement: ["Maintenance", "isAuthenticated"],
    getListOfDocuments: ["Maintenance", "isUserAuthenticated"],
    createAgreementDetail: [
      "Maintenance",
      "validation/Agreement/AgreementValidation",
    ],
    getAgreementDetailForStatic: ["Maintenance", "isUserAuthenticated"],
    getAgreementDetailForLoanAndPromissory: [
      "Maintenance",
      "isUserAuthenticated",
    ],
    getAgreementDetailForTila: ["Maintenance", "isUserAuthenticated"],
    getAgreementDetailForAdverse: ["Maintenance", "isUserAuthenticated"],
  },
  StateController: {
    createState: ["Maintenance", "validation/State/CreateStateValidation"],
    updateState: ["Maintenance", "validation/State/UpdateStateValidation"],
  },
  SettingController: {
    createSettingList: [
      "Maintenance",
      "validation/Setting/SettingcreateValidation",
    ],
    updateSetting: [
      "Maintenance",
      "validation/Setting/SettingUpdateValidation",
    ],
    getAllSetting: ["Maintenance", "validation/Setting/SettingFindValidation"],
    deleteSettingList: [
      "Maintenance",
      "validation/Setting/SettingdeleteValidation",
    ],
  },
  PaymentGatewayFundingController: {
    gatewayFunding: ["Maintenance", "basicAuth"],
    notificationforJitFunding: ["Maintenance", "basicAuth"],
  },
  PlaidUser: {
    getLatestData: ["Maintenance", "isUserAuthenticated"],
    getForUserBankAccount: ["Maintenance", "isUserAuthenticated"],
    verifyEmailId: ["Maintenance", "isUserAuthenticated"],
    getEmailVerified: ["Maintenance", "isUserAuthenticated"],
  },
  AchController: {
    saveProgramDates: ["Maintenance", "isAuthenticated"],
    showAllPendingAch: ["Maintenance", "isAuthenticated"],
    ajaxPendingAch: ["Maintenance", "isAuthenticated"],
    getAchUserDetails: ["Maintenance", "isAuthenticated"],
    confirmProcedure: ["Maintenance", "isAuthenticated"],
    getIncompleteApplication: ["Maintenance", "isAuthenticated"],
    laterAchNeedsReview: ["Maintenance", "isAuthenticated"],
    resolveAchComments: ["Maintenance", "isAuthenticated"],
    addAchComments: [
      "Maintenance",
      "isAuthenticated",
      "validation/Ach/AddAchCommentsValidation",
    ],
    uploadDocumentProof: [
      "Maintenance",
      "isAuthenticated",
      "validation/Ach/AddAchDocumentsValidation",
      "validation/Ach/ProofDocumentsValidation",
    ],
    defaultUsers: ["Maintenance", "isAuthenticated"],
    ajaxDefaultUsersList: ["Maintenance", "isAuthenticated"],
    viewDefaultUser: ["Maintenance", "isAuthenticated"],
    ajaxAchComments: ["Maintenance", "isAuthenticated"],
    showAllComplete: ["Maintenance", "isAuthenticated"],
    completeApplication: ["Maintenance", "isAuthenticated"],
    showAllBlocked: ["Maintenance", "isAuthenticated"],
    ajaxBlockedAch: ["Maintenance", "isAuthenticated"],
    releaseApp: ["Maintenance", "isAuthenticated"],
    approveUserLoan: ["Maintenance", "isAuthenticated"],
    manageReconciliation: ["Maintenance", "isAuthenticated"],
    ajaxReconciliationList: ["Maintenance", "isAuthenticated"],
    showAllDenied: ["Maintenance", "isAuthenticated"],
    ajaxDeniedApplication: ["Maintenance", "isAuthenticated"],
    viewreconciliationDetails: ["Maintenance", "isAuthenticated"],
    cancelAch: ["Maintenance", "isAuthenticated"],
    makepayment: ["Maintenance", "isAuthenticated"],
    addchargeoff: ["Maintenance", "isAuthenticated"],
    approvePatientloan: ["Maintenance", "isAuthenticated"],
    updatePatientloanstartdate: ["Maintenance", "isAuthenticated"],
    denyUserLoan: ["Maintenance", "isAuthenticated"],
    updateSetDate: ["Maintenance", "isAuthenticated"],
    showAllPerforming: ["Maintenance", "isAuthenticated"],
    showAllCompleted: ["Maintenance", "isAuthenticated"],
    showAllChargeOff: ["Maintenance", "isAuthenticated"],
    showAllArchivedDenied: ["Maintenance", "isAuthenticated"],
    showAllArchivedPendingAch: ["Maintenance", "isAuthenticated"],
    movetoopenupdate: ["Maintenance", "isAuthenticated"],
    showAllToDoItemsPendingAch: ["Maintenance", "isAuthenticated"],
    showAllToDoItemsDenied: ["Maintenance", "isAuthenticated"],
    showProcedureDateSet: ["Maintenance", "isAuthenticated"],
    markAsReviewed: ["Maintenance", "isAuthenticated"],
    showAllToDoItemsOpenApplication: ["Maintenance", "isAuthenticated"],
    showAllArchivedOpenAch: ["Maintenance", "isAuthenticated"],
    showAllOpenApplicationAch: ["Maintenance", "isAuthenticated"],
    showInCompleteApplicationAch: ["Maintenance", "isAuthenticated"],
    ajaxOpenApplicationAch: ["Maintenance", "isAuthenticated"],
    providerlist: ["Maintenance", "isAuthenticated"],
    ajaxProvider: ["Maintenance", "isAuthenticated"],
    reGeneratePaymentScheduleCalendar: ["Maintenance", "isAuthenticated"],
    savePaymentScheduleChanges: ["Maintenance", "isAuthenticated"],
    approveISA: ["Maintenance", "isAuthenticated"],
    ajaxUpdatePaymentBankruptcy: ["Maintenance", "isAuthenticated"],
    showAllBankruptcies: ["Maintenance", "isAuthenticated"],
    ajaxGetBankruptcyList: ["Maintenance", "isAuthenticated"],
    deferPaymentItem: ["Maintenance", "isAuthenticated"],
    waivePaymentItem: ["Maintenance", "isAuthenticated"],
    waiveEntireLoan: ["Maintenance", "isAuthenticated"],
    showFreshLeadsList: ["Maintenance", "isAuthenticated"],
    ajaxFreshLeadList: ["Maintenance", "isAuthenticated"],
    ajaxUpdatePaymentStatus: ["Maintenance", "isAuthenticated"],
    ajaxToggleAutoAch: ["Maintenance", "isAuthenticated"],
    /***** Leads ******/
    showLeadAch: ["Maintenance", "isAuthenticated"],
    ajaxOriginateLoan: ["Maintenance", "isAuthenticated"],
    changeFundingPaymentType: ["Maintenance", "isAuthenticated"],
    changeIncompleteFundingPaymentType: ["Maintenance", "isAuthenticated"],
    ajaxOriginateOrApproveAndFundLoan: ["Maintenance", "isAuthenticated"],
    ajaxChangeLoanDetails: ["Maintenance", "isAuthenticated"],
    ajaxUpdateUserTabInformation: ["Maintenance", "isAuthenticated"],
    ajaxUpdateEmployerTabInformation: ["Maintenance", "isAuthenticated"],
    ajaxUpdateBankAccountInformation: ["Maintenance", "isAuthenticated"],
  },
  AdminuserController: {
    changepassword: ["Maintenance", "isAuthenticated"],
    updatepassword: ["Maintenance", "isAuthenticated"],
    adminuserlist: ["Maintenance", "isAuthenticated"],
    createnewuser: ["Maintenance", "isAuthenticated"],
    addnewuser: [
      "Maintenance",
      "isAuthenticated",
      "validation/Adminuser/addnewuserValidation",
    ],
    edituser: ["Maintenance", "isAuthenticated"],
    updateuser: [
      "Maintenance",
      "isAuthenticated",
      "validation/Adminuser/edituserValidation",
    ],
    updateAdminUserStatus: ["Maintenance", "isAuthenticated"],
    resetPassword: [
      "Maintenance",
      "validation/Adminuser/resetPasswordValidation",
    ],
    ajaxadminuserlist: ["Maintenance", "isAuthenticated"],
  },
  LogactivityController: {
    manageLogActivity: ["Maintenance", "isAuthenticated"],
    ajaxManageLogList: ["Maintenance", "isAuthenticated"],
    viewlogDetails: ["Maintenance", "isAuthenticated"],
    communicationlog: ["Maintenance", "isAuthenticated"],
    managelogactivity: ["Maintenance", "isAuthenticated"],
  },
  TransUnionController: {
    transunionRegistration: ["Maintenance", "isUserAuthenticated"],
    registerCreditMonitoring: ["Maintenance", "isUserAuthenticated"],
    checkCreditMonitoring: ["Maintenance", "isUserAuthenticated"],
    updateCreditMonitoring: ["Maintenance", "isUserAuthenticated"],
    showCreditMonitoring: ["Maintenance", "isUserAuthenticated"],
    renewCreditMonitoring: ["Maintenance", "isUserAuthenticated"],
    getCreditMonitoringDetails: ["Maintenance", "isUserAuthenticated"],
    creditmonitoringusers: ["Maintenance", "isAuthenticated"],
    ajaxcreditmonitoringuserlist: ["Maintenance", "isAuthenticated"],
    viewCreditUserDetails: ["Maintenance", "isAuthenticated"],
    registernewCreditMonitoring: ["Maintenance", "isUserAuthenticated"],
  },
  HomeController: {
    achAuthorization: ["Maintenance", "isLoginAuthenticated"],
    changeScheduleAuthorization: ["Maintenance", "isLoginAuthenticated"],
    addUser: ["Maintenance", "validation/User/addnewuserValidation"],
    getthecashhome: ["Maintenance", "validation/User/AddNewUserBytfchome"],
    showHome: ["Maintenance"],
    signupstart: ["Maintenance", "isApplicationAuthenticated"],
    register: ["Maintenance"],
    userinformationfull: ["Maintenance", "isApplicationAuthenticated"],
    userinformationfullmanual: ["Maintenance", "isApplicationAuthenticated"],
    financeinformation: ["Maintenance", "isApplicationAuthenticated"],
    financeinformationdata: ["Maintenance", "isApplicationAuthenticated"],
    loanofferdetails: ["Maintenance"],
    applicationoffer: ["Maintenance"],
    saveapplicationoffer: ["Maintenance"],
    loanpromissorynote: ["Maintenance"],
    createloanpromissorypdf: ["Maintenance"],
    createloanapplication: ["Maintenance"],
    success: ["Maintenance"],
    controlcenter: ["Maintenance"],
    userinformationfullform: [
      "Maintenance",
      "isApplicationAuthenticated",
      "validation/User/addnewuserValidation",
    ],
    autocompleteBankname: ["Maintenance"],
    verifyUser: ["Maintenance"],
    willLogin: ["Maintenance"],
    login: ["Maintenance"],
    setpassword: ["Maintenance"],
    updatepassword: ["Maintenance"],
    cosignupstart: ["Maintenance"],
    loansuccess: ["Maintenance"],
    loanfailure: ["Maintenance"],
    editprofile: ["Maintenance", "isLoginAuthenticated"],
    downloadconsentpdf: ["Maintenance"],
    forgotpassword: ["Maintenance"],
    chatsupport: ["Maintenance"],
    profileEmailverification: ["Maintenance"],
    profileEmailverify: ["Maintenance"],
    contactus: ["Maintenance"],
    privacypolicy: ["Maintenance"],
    termsconditions: ["Maintenance"],
    userlogout: ["Maintenance"],
    logout: ["Maintenance"],
    loanamountconfirm: ["Maintenance"],
    apply: ["Maintenance"],
    applyPost: ["Maintenance"],
    practiceApplication: ["Maintenance"],
    createApplication: ["Maintenance"],
    createApplicationPost: ["Maintenance"],
    searchpractice: ["Maintenance"],
    applysearch: ["Maintenance"],
    addprovider: ["Maintenance"],
    addnewprovider: ["Maintenance"],
    providersuccess: ["Maintenance"],
    setSelectedPractice: ["Maintenance"],
    paymentcalculator: ["Maintenance", "isApplicationAuthenticated"],
    estimatemonthlypay: ["Maintenance", "isApplicationAuthenticated"],
    continueApplication: ["Maintenance", "isApplicationAuthenticated"],
    updateuserAnticipatedAmount: ["Maintenance", "isApplicationAuthenticated"],
    clicktosave: ["Maintenance", "isApplicationAuthenticated"],
    onclicktosave: ["Maintenance", "isApplicationAuthenticated"],
    updateuseremail: ["Maintenance", "isLoginAuthenticated"],
    sendverificationemail: ["Maintenance"],
    dashboard: ["Maintenance", "isLoginAuthenticated"],
    updateEmploymentHistory: ["Maintenance", "isAuthenticated"],
    skipBankLogin: ["Maintenance"],
  },
  CustomerServiceController: {
    addNewUserByCustomerService: [
      "Maintenance",
      "validation/User/AddNewUserByCustomerServiceValidation",
    ],
    addApplicationByCustomerService: ["Maintenance", "isAuthenticated"],
    transUnionInfoByCustomerService: ["Maintenance", "isAuthenticated"],
    addbankaccount: ["Maintenance", "isLoginAuthenticated"],
    saveincomedetails: ["Maintenance", "isLoginAuthenticated"],
    servicetransaction: ["Maintenance", "isLoginAuthenticated"],
    emailselectedAccount: ["Maintenance", "isLoginAuthenticated"],
    csmyoffer: ["Maintenance", "isLoginAuthenticated"],
    myoffers: ["Maintenance", "isLoginAuthenticated"],
    userpromissorynote: ["Maintenance", "isLoginAuthenticated"],
    createpromissorypdf: ["Maintenance", "isLoginAuthenticated"],
    filloutfinancedata: ["Maintenance", "isLoginAuthenticated"],
    borrowerloanamountconfirm: ["Maintenance", "isLoginAuthenticated"],
  },
  AdminApplicationController: {
    addApplication: ["Maintenance"],
    addLoan: ["Maintenance"],
    getPractices: ["Maintenance"],
    getStates: ["Maintenance"],
    selectOffer: ["Maintenance"],
    getOffers: ["Maintenance"],
  },
  ApplicationController: {
    userinformation: ["Maintenance"],
    application: ["Maintenance"],
    createApplication: ["Maintenance"],
    createApplicationPost: ["Maintenance"],
    applicationWaterfall: ["Maintenance"],
    createEmploymentAndReference: ["Maintenance"],
    getEmploymentAndReference: ["Maintenance", "isLoginAuthenticated"],
    emailverifylanding: ["Maintenance"],
    adddocument: [
      "Maintenance",
      "validation/Application/uploaddocumentValidation",
    ],
    createstateregulation: [
      "Maintenance",
      "validation/State/CreateLoanStateValidation",
    ],
    promissorynote: ["Maintenance", "isLoginAuthenticated"],
    contract: ["Maintenance", "isLoginAuthenticated"],
    contractSigned: ["Maintenance", "isdashboardAuthenticated"],
    resignChangeScheduleContract: ["Maintenance", "isdashboardAuthenticated"],
    redirecttodashboard: ["Maintenance", "isdashboardAuthenticated"],
    denyLoan: ["Maintenance"],
    saveSignature: ["Maintenance"],
    couserinformation: ["Maintenance"],
    couserinformationfull: ["Maintenance"],
    cofinancialinfomation: ["Maintenance"],
    sendforgotpassword: ["Maintenance"],
    usersetpassword: ["Maintenance"],
    updateuserpassword: ["Maintenance"],
    savechangepassword: ["Maintenance"],
    receivenotifi: ["Maintenance"],
    uploadAvatar: ["Maintenance"],
    uploaddropfiles: ["Maintenance"],
    createpromissorypdf: ["Maintenance", "isLoginAuthenticated"],
    signAchDebit: ["Maintenance"],
    displayErrorPage: ["Maintenance"],
    postOffers: ["Maintenance"],
    leadUserNewPassword: ["Maintenance"],
    reApplyApplication: ["Maintenance", "isAuthenticated"],
    reApplyOffers: ["Maintenance", "isAuthenticated"],
    ajaxReApplyOfferSubmission: ["Maintenance", "isAuthenticated"],
    ajaxPostReApplyApplication: ["Maintenance", "isAuthenticated"],
    leadCreateAccount: ["Maintenance"],
    leadCreateAccountPost: ["Maintenance"],
    postVerifyBankInfo: ["Maintenance", "isdashboardAuthenticated"],
    getLeadBankInfo: ["Maintenance", "isdashboardAuthenticated"],
    denyReapplication: ["Maintenance", "isAuthenticated"],
    allowReApplication: ["Maintenance", "isAuthenticated"],
  },
  OffersController: {
    getOffersPage: ["Maintenance", "isLoginAuthenticated"],
    getOffersByUser: ["Maintenance"],
  },
  EsignatureController: {
    saveSignature: ["Maintenance", "isdashboardAuthenticated"],
    acceptTerm: ["Maintenance", "isdashboardAuthenticated"],
    createSignedDocuments: ["Maintenance", "isdashboardAuthenticated"],
    getUserSignatureContent: ["Maintenance", "isdashboardAuthenticated"],
    getUserLoanDocument: ["Maintenance"],
  },
  BankController: {
    getFlinksAccountDetail: ["Maintenance"],
    storeFlinksLoginId: ["Maintenance"],
    getbanktransaction: ["Maintenance"],
    addBankTransaction: ["Maintenance", "isAddBankAuthenticated"],
    saveplaiddetails: ["Maintenance"],
    updateUserdataPlaid: ["Maintenance"],
    saveplaidresponse: ["Maintenance"],
    selectedAccount: ["Maintenance"],
    savebankinfo: ["Maintenance", "isAuthenticated"],
    addbanklogin: ["Maintenance", "isAddBankAuthenticated"],
    addbankloginpost: ["Maintenance", "isAddBankAuthenticated"],
    addbankGetConsent: ["Maintenance", "isAddBankAuthenticated"],
    addbankSaveConsent: ["Maintenance", "isAddBankAuthenticated"],
    addbankThankyou: ["Maintenance", "isAddBankAuthenticated"],
    changeBank: ["Maintenance", "isAuthenticated"],
    repullPlaidInfo: ["Maintenance", "isAuthenticated"],
    getrepullPlaidDetails: ["Maintenance", "isAuthenticated"],
    verifyBankAuthorization: ["Maintenance"],
    manualBankAdd: ["Maintenance"],
    listUserAchAccounts: ["Maintenance"],
  },
  ScreentrackingController: {
    getIncompleteApplication: ["Maintenance", "isAuthenticated"],
    addScreentrackingComments: [
      "Maintenance",
      "isAuthenticated",
      "validation/Screentracking/ScreentrackingCommentsValidation",
    ],
    incompleteDenyUserLoan: ["Maintenance", "isAuthenticated"],
    ajaxIncompleteList: ["Maintenance", "isAuthenticated"],
    viewIncomplete: ["Maintenance", "isAuthenticated"],
    getChangeLoanOfferDetails: ["Maintenance", "isAuthenticated"],
    updateNewloanincomedetails: ["Maintenance", "isAuthenticated"],
    ajaxScreentrackingComments: ["Maintenance"],
    ajaxAllusersComments: ["Maintenance"],
    addAlluserComments: ["Maintenance", "isAuthenticated"],
    incompletegetrepullPlaidDetails: ["Maintenance", "isAuthenticated"],
    manualLoanOfferDetails: ["Maintenance", "isAuthenticated"],
    savemanualLoanOfferDetails: ["Maintenance", "isAuthenticated"],
    ArchivedIncompleteApplication: ["Maintenance", "isAuthenticated"],
    movetoincompleteupdate: ["Maintenance", "isAuthenticated"],
    ToDoItemIncompleteApplication: ["Maintenance", "isAuthenticated"],
    markToIncompleteApp: ["Maintenance", "isAuthenticated"],
    movetoarchive: ["Maintenance", "isAuthenticated"],
    unarchive: ["Maintenance", "isAuthenticated"],
    adminAddUpdateReferences: ["Maintenance", "isAuthenticated"],
    ajaxSendLeadInviteEmail: ["Maintenance", "isAuthenticated"],
    ajaxSendResignEmail: ["Maintenance", "isAuthenticated"],
  },
  CategoryController: {
    getDashboardView: ["Maintenance", "isAuthenticated"],
  },
  UtilityController: {
    getStates: ["Maintenance"],
  },
  PracticeController: {
    practiceList: ["Maintenance", "isAuthenticated"],
    createpractice: ["Maintenance", "isAuthenticated"],
    addnewpractice: ["Maintenance", "isAuthenticated"],
    ajaxpracticeList: ["Maintenance", "isAuthenticated"],
    editpractice: ["Maintenance", "isAuthenticated"],
    updatepractice: ["Maintenance", "isAuthenticated"],
    practiceLogActivity: ["Maintenance", "isAuthenticated"],
    staffAdminList: ["Maintenance", "isAuthenticated"],
    ajaxstaffAdminUserList: ["Maintenance", "isAuthenticated"],
    addnewstaffAdminUser: ["Maintenance", "isAuthenticated"],
    editstaffAdminuser: ["Maintenance", "isAuthenticated"],
    updatestaffAdminUser: ["Maintenance", "isAuthenticated"],
    addStaffAdmin: ["Maintenance", "isAuthenticated"],
    autoFillingUniversity: ["Maintenance", "isAuthenticated"],
    getschoolBranch: ["Maintenance", "isAuthenticated"],
    startPractice: ["Maintenance", "isPracticeAuthenticated"],
    resendinvite: ["Maintenance", "isAuthenticated"],
    checkpracticeurl: ["Maintenance", "isAuthenticated"],
    updatepracticeinfo: ["Maintenance"],
    createprocedure: ["Maintenance"],
    deleteprocedure: ["Maintenance"],
    updateprocedure: ["Maintenance"],
    addlendermerchantfees: ["Maintenance"],
    getmerchantfeetemplate: ["Maintenance"],
    getvendorinterestrate: ["Maintenance"],
    addstaffmembers: ["Maintenance"],
    getstaffmembers: ["Maintenance"],
    addfinancialinformation: ["Maintenance"],
    viewpracticedetails: ["Maintenance", "isAuthenticated"],
    practicesettingEdit: ["Maintenance", "isAuthenticated"],
  },
  StaffportalController: {
    setpassword: ["Maintenance"],
    updatepassword: ["Maintenance"],
    login: ["Maintenance"],
    signin: ["Maintenance"],
  },
  TestController: {
    getLatestPdfReport: ["Maintenance"],
    testClarityServiceCalls: ["Maintenance"],
    testFactorTrustLendProtect: ["Maintenance"],
    testUnderwriting: ["Maintenance"],
    testUnderwritingEmails: ["Maintenance"],
    regeneratePaymentSchedule: ["Maintenance"],
    processNachaPayments: ["Maintenance"],
    processNachaReturnFile: ["Maintenance"],
    testSmoothPaymentGeneration: ["Maintenance"],
    testChangingPaymentSchedule: ["Maintenance"],
    insertTestData: ["Maintenance"],
    testNachaUploadFile: ["Maintenance"],
    testAuth: ["Maintenance"],
  },
  InstitutionController: {
    getPlaidTransactions: [],
  },
  BorrowerController: {
    // dashboard: ["Maintenance", "isLoginAuthenticated"],
    // createnewapplication: ["Maintenance", "isLoginAuthenticated"],
    // getApploanDetails: ["Maintenance", "isLoginAuthenticated"],
    // updatenewapplication: ["Maintenance", "isLoginAuthenticated"],
    borrowerLogin: ["Maintenance"],
    getBorrowerData: ["Maintenance", "isdashboardAuthenticated"],
    getBorrowerAgreements: ["Maintenance"],
    readAgreement: ["Maintenance"],
  },
  PracticereportController: {
    showPracticeReportList: ["Maintenance", "isAuthenticated"],
    ajaxCreditReportList: ["Maintenance", "isAuthenticated"],
  },
  CollectionsController: {
    getCollectionsView: [
      "Maintenance",
      "isAuthenticated",
      "collections/hasCollectionsAccess",
    ],
    ajaxGetCollectionsData: [
      "Maintenance",
      "isAuthenticated",
      "collections/hasCollectionsAccess",
    ],
    ajaxAssignToUser: [
      "Maintenance",
      "isAuthenticated",
      "collections/hasCollectionManagerAccess",
    ],
    getPassDuePaymentsForDisplay: [
      "Maintenance",
      "isAuthenticated",
      "collections/hasCollectionsAccess",
    ],
    ajaxGetPassDuePayments: [
      "Maintenance",
      "isAuthenticated",
      "collections/hasCollectionsAccess",
    ],
    changePromiseToPaySchedule: [
      "Maintenance",
      "isAuthenticated",
      "collections/hasCollectionManagerAccess",
    ],
    ajaxGetCollectionComments: [
      "Maintenance",
      "isAuthenticated",
      "collections/hasCollectionsAccess",
    ],
    ajaxUpdatePaymentWorkFlow: [
      "Maintenance",
      "isAuthenticated",
      "collections/hasCollectionsAccess",
    ],
    ajaxGetNewPaymentSchedulePreview: [
      "Maintenance",
      "isAuthenticated",
      "collections/hasCollectionsAccess",
    ],
    ajaxSaveNewLoanModifications: [
      "Maintenance",
      "isAuthenticated",
      "collections/hasCollectionsAccess",
    ],

    showSettledContacts: ["Maintenance", "isAuthenticated"],
    showChargedOffContacts: ["Maintenance", "isAuthenticated"],
    ajaxGetEndedContractsList: ["Maintenance", "isAuthenticated"],

    ajaxGetModifiedLoansList: ["Maintenance", "isAuthenticated"],
    showModifiedLoans: ["Maintenance", "isAuthenticated"],

    showLoanModificationPage: [
      "Maintenance",
      "isAuthenticated",
      "collections/hasCollectionsAccess",
    ],

    //TODO: DELETE ME WHEN VIKING ACH IS TESTED AND DONE
    testProcessPayments: ["Maintenance"],
    testCheckPaymentStatus: ["Maintenance"],
  },
  PaymentController: {
    makePaymentRenderDialog: ["Maintenance", "isAuthenticated"],
    submitPayment: ["Maintenance", "isAuthenticated"],
    deletePaymentScheduleTransaction: ["Maintenance", "isAuthenticated"],
  },
  ReportController: {
    reports: ["Maintenance", "isAuthenticated"],
    createAndDownloadPaymentReport: ["Maintenance", "isAuthenticated"],
    reportShow: ["Maintenance", "isAuthenticated"],
    generateReport: ["Maintenance", "isAuthenticated"],
    reportHistory: ["Maintenance", "isAuthenticated"],
    downloadReport: ["Maintenance", "isAuthenticated"],
  },
  JWTController: {
    // generateJWT: [ "Maintenance", "isAuthenticated" ]
    generateJWT: ["Maintenance"],
  },
  LeadController: {
    considerLead: ["validation/Lead/LeadImportValidation"], //apiKeyAuth ? 
    getLeadStats: ["Maintenance", "isAuthenticated"],
    getLeadControllerUI: ["Maintenance", "isAuthenticated"],
    getCampaignStats: ["Maintenance", "isAuthenticated"],
    setDayLimit: ["Maintenance", "isAuthenticated"],
    getDayLimit: ["Maintenance", "isAuthenticated"],
    setMonthLimit: ["Maintenance", "isAuthenticated"],
    getMonthLimit: ["Maintenance", "isAuthenticated"],
    setHourLimit: ["Maintenance", "isAuthenticated"],
    getHourLimit: ["Maintenance", "isAuthenticated"],
    setCampaignDayLimit: ["Maintenance", "isAuthenticated"],
    getCampaignDayLimit: ["Maintenance", "isAuthenticated"],
    setCampaignMonthLimit: ["Maintenance", "isAuthenticated"],
    getCampaignMonthLimit: ["Maintenance", "isAuthenticated"],
    setPurchaseBool: ["Maintenance", "isAuthenticated"],
    getPurchaseBool: ["Maintenance", "isAuthenticated"],
    SetPurchaseHolidaysBool: ["Maintenance", "isAuthenticated"],
    SetPurchaseWeekendsBool: ["Maintenance", "isAuthenticated"],
    SetPurchaseHoursRange: ["Maintenance", "isAuthenticated"],
    getConfig: ["Maintenance", "isAuthenticated"],
    getRejectedLeadUI: ["Maintenance", "isAuthenticated"],
    getRejectedLeads: ["Maintenance", "isAuthenticated"],
    getRejectedDetails: ["Maintenance", "isAuthenticated"],
    ajaxGetDeniedLeadApiData: ["Maintenance", "isAuthenticated"],
    setCampaignAutoPromote: ["Maintenance", "isAuthenticated"],
  },
  NachaController: {
    nachaFiles: ["Maintenance", "isAuthenticated"],
    nachaFileList: ["Maintenance", "isAuthenticated"],
    nachaFile: ["Maintenance", "isAuthenticated"],
    nachaUpdateForm: ["Maintenance", "isAuthenticated"],
    postNachaCredentials: ["Maintenance", "isAuthenticated"],
  },
  ApiApplicationController: {
    createApplication: ["Maintenance"],
    processUnderwritingStep: ["Maintenance"],
    createEmploymentHistory: ["Maintenance"],
    getEmploymentHistory: ["Maintenance"],
    updateEmployerInfo: ["Maintenance"],
    updateUserInfo: ["Maintenance"],
    getUserInfo: ["Maintenance"],
    updateUserFinancialInfo: ["Maintenance"],
    createApplicationOffers: ["Maintenance"],
    getApplicationOffers: ["Maintenance"],
    saveOffers: ["Maintenance"],
    uploadLoanDocument: ["Maintenance"],
    storeInitialSelectedOffer: [
      "Maintenance",
      "validation/Offer/StoreOfferValidation",
    ],
    confirmApplicationReview: ["Maintenance"],
    sendKbaAnswers: ["Maintenance", "validation/TrueValidate/KbaQuestionsResponses"],
    sendOtpResponse: ["Maintenance", "validation/TrueValidate/OtpCode"],
    getUserKbaQuestions: ["Maintenance"],
    getTrueValidateStatus: ["Maintenance"],
    getOtpStatus: ["Maintenance"],
    resendOtpCode: ["Maintenance"],
  },
};
